services:

  frontend:
    build: ./frontend
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app-network

  database:
    image: postgres:16-alpine
    restart: unless-stopped
   environment:
  POSTGRES_USER: ${POSTGRES_USER:-postgres}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
  POSTGRES_DB: ${POSTGRES_DB:-devopsdb}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  nginx:
    build: ./nginx
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
