
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: backend
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        working-directory: backend
        run: |
          pytest

  docker-build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Backend Docker image
        run: |
          docker build -t devops-cloud-backend ./backend

      - name: Build Frontend Docker image
        run: |
          docker build -t devops-cloud-frontend ./frontend

      - name: Build Nginx Docker image
        run: |
          docker build -t devops-cloud-nginx ./nginx

